"""Feasibility check for an LS2 inversion inside the thesis stack.

Context.  In round 1 of the qualifying-exam Q&A (`claude_prompts/qual_exam_prompts.md`,
A1) the advisor asked to "create our own LS2 algorithm as described in
`loisel_stramski2000.pdf`".  LS2 needs, per wavelength, the remote-sensing
reflectance Rrs, the diffuse attenuation coefficient Kd averaged over the first
attenuation depth (<Kd>_1), the solar zenith angle, and pure-water aw/bw plus
particulate bp.  BING needs only Rrs.  Whether the corpora IOPtics already uses
can supply <Kd>_1 therefore decides whether LS2 can be benchmarked head to head
with BING at all, and on which corpus.

This script answers that question from the data on disk.  It does three things:

1.  Reports which LS2 inputs each corpus exposes (L23, PANGAEA, GLORIA).
2.  For L23, computes <Kd>_1(lambda) for every scenario from the Hydrolight
    profile file -- KEd_z integrated/averaged from the surface to the
    per-wavelength first attenuation depth z1_lambda -- and reports coverage and
    a few summary statistics.
3.  Writes the resulting <Kd>_1 table to a .npz next to the L23 data so that a
    later IOPtics LS2 adapter can consume it without redoing the integration.

Run in the `ocean14` environment:

    conda run -n ocean14 python claudes_phd_thesis/scripts/ls2_feasibility.py

Output: `reports/ls2_feasibility.md` (and, with --write-kd, the .npz).
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[2]
REPORT = REPO / "reports" / "ls2_feasibility.md"

# LS2 inputs, in the order LS2_main() takes them.
LS2_INPUTS = ["sza", "lambda", "Rrs", "Kd (<Kd>_1)", "aw", "bw", "bp"]


def os_color() -> Path:
    root = os.environ.get("OS_COLOR")
    if not root:
        sys.exit("OS_COLOR is not set; source the shell profile first.")
    return Path(root)


def mean_kd_first_attenuation_depth(ds):
    """<Kd>_1(scenario, lambda) from the L23 profile file.

    L23 stores ``KEd_z(z, IOP_Scenario, Lambda)`` and the per-wavelength first
    attenuation depth ``z1_lambda(Lambda, IOP_Scenario)``, with -999 as the fill
    value.  Loisel & Stramski define <Kd>_1 as Kd averaged between the sea
    surface and z1; we take the trapezoidal depth-average of KEd_z over
    0 <= z <= z1, which is robust to the profile not being a pure exponential in
    the top metre.  Fully vectorised: the depth grid is shared, so the only
    per-pair work is locating z1 in it.
    """
    z = np.asarray(ds["z"].values, dtype=float)
    keep = z >= 0.0
    zs = z[keep]                                                  # (nz,)
    ked = np.asarray(ds["KEd_z"].values, dtype=float)[keep]       # (nz, ns, nlam)
    ked = np.moveaxis(ked, 0, -1)                                 # (ns, nlam, nz)
    z1 = np.asarray(ds["z1_lambda"].values, dtype=float).T        # (ns, nlam)
    z1 = np.where((z1 > 0) & (z1 <= zs[-1]), z1, np.nan)

    # Cumulative trapezoidal integral of KEd_z along depth.
    dz = np.diff(zs)
    seg = 0.5 * (ked[..., 1:] + ked[..., :-1]) * dz                # (ns, nlam, nz-1)
    cum = np.concatenate([np.zeros(seg.shape[:-1] + (1,)), np.cumsum(seg, axis=-1)],
                         axis=-1)                                  # (ns, nlam, nz)

    # Locate z1 in the shared depth grid and add the partial final segment.
    z1f = np.where(np.isfinite(z1), z1, zs[0])
    i = np.clip(np.searchsorted(zs, z1f, side="right") - 1, 0, len(zs) - 2)
    ns, nlam = z1.shape
    si = np.arange(ns)[:, None]
    sj = np.arange(nlam)[None, :]
    z_lo, z_hi = zs[i], zs[i + 1]
    k_lo = cum[si, sj, i]
    ked_lo, ked_hi = ked[si, sj, i], ked[si, sj, i + 1]
    frac = (z1f - z_lo) / (z_hi - z_lo)
    ked_at = ked_lo + frac * (ked_hi - ked_lo)
    integral = k_lo + 0.5 * (ked_lo + ked_at) * (z1f - z_lo)

    out = integral / z1f
    return np.where(np.isfinite(z1) & np.isfinite(out), out, np.nan)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--X", type=int, default=4,
                    help="L23 inelastic scenario: 1 elastic, 2 +Raman, 4 +fluorescence")
    ap.add_argument("--write-kd", action="store_true",
                    help="write <Kd>_1 to $OS_COLOR/Loisel2023/L23_mean_Kd1_X{X}.npz")
    args = ap.parse_args()

    import xarray as xr

    root = os_color()
    l23 = root / "Loisel2023"
    prof = l23 / f"Hydrolight{args.X}00_profile.nc"
    main_nc = l23 / f"Hydrolight{args.X}00.nc"

    lines = ["# LS2 feasibility on the thesis corpora", ""]
    lines.append(f"Generated by `claudes_phd_thesis/scripts/ls2_feasibility.py` "
                 f"(L23 X={args.X}).  LS2 inputs: " + ", ".join(LS2_INPUTS) + ".")
    lines.append("")

    # --- 1. corpus-by-corpus input availability -------------------------------
    lines.append("## Input availability by corpus")
    lines.append("")
    lines.append("| corpus | Rrs | <Kd>_1 | sza | bp | verdict |")
    lines.append("|---|---|---|---|---|---|")

    ds_main = xr.load_dataset(main_nc, engine="h5netcdf")
    ds_prof = xr.load_dataset(prof, engine="h5netcdf")
    have_kd = "KEd_z" in ds_prof.variables and "z1_lambda" in ds_prof.variables
    have_bp = "bph" in ds_main.variables or "bnw" in ds_main.variables
    lines.append(
        f"| L23 (X={args.X}, {ds_main.sizes.get('IOP_Scenario', '?')} scenarios) | yes | "
        f"{'yes (KEd_z + z1_lambda, profile file)' if have_kd else 'NO'} | "
        "yes (0/30/60 deg by scenario) | "
        f"{'yes (bnw/bph truth)' if have_bp else 'NO'} | "
        f"{'**testable, with truth**' if (have_kd and have_bp) else 'blocked'} |")
    lines.append("| PANGAEA/Valente | yes | measured Kd in `insitudb_iopskdtsm_V3` "
                 "(ocpy `pangaea.py` maps `KD`->`kd`) -- but at the *in-situ* depth "
                 "convention, not necessarily <Kd>_1 | station metadata | no (bbp only) | "
                 "testable with caveats |")
    lines.append("| GLORIA | yes | not loaded by ocpy | station metadata | no | "
                 "blocked without an empirical Kd |")
    lines.append("")

    if not have_kd:
        REPORT.write_text("\n".join(lines) + "\n")
        print(f"wrote {REPORT} (L23 has no Kd; stopping)")
        return

    # --- 2. compute <Kd>_1 on L23 --------------------------------------------
    kd1 = mean_kd_first_attenuation_depth(ds_prof)
    lam = np.asarray(ds_prof["Lambda"].values, dtype=float)
    ns, nlam = kd1.shape
    finite = np.isfinite(kd1)

    lines.append("## `<Kd>_1` computed from L23")
    lines.append("")
    lines.append(f"- scenarios x wavelengths: {ns} x {nlam} "
                 f"({lam.min():.0f}-{lam.max():.0f} nm)")
    lines.append(f"- finite values: {finite.sum()} / {finite.size} "
                 f"({100*finite.mean():.2f}%)")
    lines.append(f"- scenarios with a complete spectrum: "
                 f"{int(finite.all(axis=1).sum())} / {ns}")
    lines.append("")
    lines.append("| wavelength | median <Kd>_1 [1/m] | 5th pct | 95th pct | n finite |")
    lines.append("|---|---|---|---|---|")
    for target in (440.0, 490.0, 555.0, 670.0):
        j = int(np.argmin(np.abs(lam - target)))
        col = kd1[:, j]
        c = col[np.isfinite(col)]
        if c.size == 0:
            lines.append(f"| {lam[j]:.0f} nm | - | - | - | 0 |")
            continue
        lines.append(f"| {lam[j]:.0f} nm | {np.median(c):.4f} | "
                     f"{np.percentile(c, 5):.4f} | {np.percentile(c, 95):.4f} | {c.size} |")
    lines.append("")
    lines.append("Conclusion: LS2 can be run over the full L23 corpus against exact "
                 "truth for total `a` and `bb`, using the same 3,320 water bodies the "
                 "RT-A sweep used.  It cannot be asked for `a_ph`/`a_dg` at all -- "
                 "LS2 returns totals and `anw`/`bbp` only -- which is precisely the "
                 "head-to-head the Q1 separation claim predicts the outcome of.")
    lines.append("")

    REPORT.parent.mkdir(exist_ok=True)
    REPORT.write_text("\n".join(lines) + "\n")
    print(f"wrote {REPORT}")

    if args.write_kd:
        out = l23 / f"L23_mean_Kd1_X{args.X}.npz"
        np.savez_compressed(out, Kd1=kd1, Lambda=lam)
        print(f"wrote {out}")


if __name__ == "__main__":
    main()
